export const SERVER_SECRET_ENV_NAMES = [
  "DATABASE_URL",
  "CLERK_SECRET_KEY",
  "CLERK_WEBHOOK_SECRET",
  "CLERK_WEBHOOK_SIGNING_SECRET",
  "ALCHEMY_STELLAR_API_KEY",
  "STELLAR_HOT_WALLET_SECRET",
  "CERTIFICATE_WORKER_TOKEN",
] as const;
