export const SERVER_SECRET_ENV_NAMES = [
  "DATABASE_URL",
  "CLERK_SECRET_KEY",
  "CLERK_WEBHOOK_SECRET",
  "CLERK_WEBHOOK_SIGNING_SECRET",
  "S3_ACCESS_KEY_ID",
  "S3_SECRET_ACCESS_KEY",
  "STORAGE_URL_SIGNING_SECRET",
  "ALCHEMY_STELLAR_API_KEY",
  "STELLAR_HOT_WALLET_SECRET",
] as const;
